//
// OpenMP (task-based) implementation for the One-Shot project:
//
//   Iterative Sparse Matrix-Vector Computation on Evolving Sparse Matrices
//
// This is the second required deliverable: an OpenMP version *based on tasks*.
// It is a parallel counterpart of the sequential reference (iterative_SpMV.cpp)
// and preserves the same algorithmic structure, matrix generation and vector
// initialization, so results match the sequential baseline within a numerical
// tolerance (the strict bitwise checksum may differ from the C++ threads
// version because the task reduction combines partial sums in a different
// order; that is expected and acceptable per the project's tolerance rule).
//
// Parallelization strategy (OpenMP tasks)
// ---------------------------------------
//   * One persistent parallel region (#pragma omp parallel) wraps the whole
//     timed iterative loop, so the thread team is created once.
//   * Each iteration's work is generated by a single thread (#pragma omp single)
//     as OpenMP TASKS via `taskloop`; the rest of the team executes them. This
//     is the course-idiomatic parallel -> single -> taskloop pattern
//     (Code/spmcode9/omp_taskloop.cpp, omp_dotprod_taskloop.cpp). taskloop is
//     NOT a worksharing construct, so it must be generated by a single thread:
//     otherwise every thread would generate the full task set.
//   * The shifted SpMV map is fused with the L2-norm sum-of-squares using a
//     `taskloop reduction(+: ss)` (OpenMP 5; Code/spmcode9/omp_dotprod_taskloop
//     and omp_task_reduction.cpp). taskloop has an implicit taskgroup, so the
//     reduction is complete when the construct returns.
//   * Scaling is a second `taskloop`. The implicit barrier at the end of the
//     `single` then synchronizes the team before the next iteration reads the
//     buffer just written.
//   * Two ping-pong buffers replace the explicit x/y swap; the logical row shift
//     of the evolving matrix is derived locally from the iteration index.
//
// Load balancing: unlike the C++ threads version (which uses a hand-computed
// nnz-balanced static partition of the rows), here the OpenMP runtime chops the
// row range into many `grainsize` tasks and load-balances them dynamically
// across the team -- the OpenMP-native answer to nonzero imbalance. The grain
// is chosen so the number of tasks is several times the number of threads; it
// can be overridden with the GRAIN environment variable for tuning.
//
// Thread affinity (the analogue of the threads version's pinning) is expressed
// through the standard OpenMP environment rather than in code, e.g.
//   OMP_PROC_BIND=close OMP_PLACES=cores
// (course example Code/spmcode8/omp_affinity.cpp; SPM NOTES affinity section).
//
// Command line (same as the sequential / threads versions):
//   -n  N        matrix size, NxN
//   -nz K        total number of nonzeros
//   -m  mode     regular | irregular
//   -s  seed     optional seed, default 111
//   -t  T        optional number of threads (default: OMP runtime default)
//   --dump-vector FILE
//                 optional dump of the final normalized vector
//
// Build:
//   g++ -O3 -std=c++20 -pthread -fopenmp -I include
//       src/openmp/iterative_SpMV_omp.cpp -o bin/omp
//   (or: make omp)
//
// Examples:
//   ./bin/omp -n 500000 -nz 20000000 -m irregular -t 8
//   OMP_PROC_BIND=close OMP_PLACES=cores ./bin/omp -n 500000 -nz 20000000 -t 16
//   GRAIN=4096 ./bin/omp -n 100000 -nz 4000000 -m irregular -t 8
//

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <string>
#include <utility>
#include <vector>

#include <omp.h>

#include "matrix_generation.hpp"
#include "utils.hpp"


// number of iterations
static constexpr std::uint32_t NUM_ITERS = 500;
// number of iterations between two matrix-evolution steps
static constexpr std::uint32_t EPOCH_LEN = 25;


// Vector operations (used only for the serial vector initialization, exactly
// as in the sequential reference).

static double dot(const std::vector<double>& a, const std::vector<double>& b) {
    return std::inner_product(a.begin(), a.end(), b.begin(), 0.0);
}

static double l2_norm(const std::vector<double>& x) {
    return std::sqrt(dot(x, x));
}

static void normalize(std::vector<double>& x) {
    const double nrm = l2_norm(x);
    const double inv = 1.0 / nrm;

    for (double& v : x) {
        v *= inv;
    }
}


// Computes the epoch parameter (identical to the sequential reference).
static std::size_t compute_shift_rows(std::size_t n) {
    std::size_t s = n / 16 + 17;
    if ((s % 2) == 0) ++s;
    s %= n;
    if (s == 0) s = 1;
    return s;
}


// Resolve the taskloop grainsize: GRAIN env override, else a value that yields
// roughly (threads * 8) tasks so the runtime can load-balance the irregular
// nonzero distribution dynamically.
static std::size_t resolve_grain(std::size_t n, unsigned P) {
    if (const char* env = std::getenv("GRAIN")) {
        if (*env) {
            const long g = std::strtol(env, nullptr, 10);
            if (g > 0) return static_cast<std::size_t>(g);
        }
    }
    std::size_t grain = n / (static_cast<std::size_t>(P) * 8);
    if (grain == 0) grain = 1;
    return grain;
}


struct IterativeResult {
    double rayleigh             = 0.0;
    std::uint64_t checksum      = 0;
    std::size_t final_row_shift = 0;
};


static IterativeResult iterative_spmv_evolving_omp(const CSRMatrix& A,
                                                   std::uint64_t seed,
                                                   unsigned num_threads,
                                                   std::vector<double>* final_vector) {
    const std::size_t n = A.n;
    const std::size_t shift_rows = compute_shift_rows(n);

    // Phase 1: serial vector initialization, identical to the sequential
    // reference, so that the initial vector (and thus the result) matches.
    std::vector<double> buf0(n);
    std::vector<double> buf1(n, 0.0);

    SplitMix64 rng(seed ^ 0x123456789abcdef0ULL);
    for (double& v : buf0) {
        v = rng.next_unit();
    }
    normalize(buf0);

    // CSR arrays, hoisted out of the loop.
    const std::uint64_t* rp = A.row_ptr.data();
    const std::uint32_t* ci = A.col_idx.data();
    const double*        va = A.values.data();

    const std::size_t grain = resolve_grain(n, num_threads);

    double rayleigh = 0.0;

    // Phase 2: timed iterative loop. One parallel region for the whole loop;
    // a single thread generates the per-iteration tasks, the team executes them.
    #pragma omp parallel num_threads(num_threads) \
        shared(buf0, buf1, rayleigh)
    {
        for (std::uint32_t iter = 0; iter < NUM_ITERS; ++iter) {
            #pragma omp single
            {
                // Logical row shift for this iteration (same cumulative shift as
                // the sequential reference: updated every EPOCH_LEN iterations).
                const std::size_t epochs = iter / EPOCH_LEN;
                const std::size_t shift  = (shift_rows * epochs) % n;

                // Ping-pong buffers: read from one, write to the other.
                const double* xr = ((iter & 1u) == 0u) ? buf0.data() : buf1.data();
                double*       yw = ((iter & 1u) == 0u) ? buf1.data() : buf0.data();

                // Phase A: shifted SpMV map over the source rows, fused with the
                // sum-of-squares accumulation for the L2 norm, expressed as a
                // task reduction. The taskloop's implicit taskgroup makes `ss`
                // complete when the construct returns.
                double ss = 0.0;
                #pragma omp taskloop grainsize(grain) reduction(+: ss) \
                    default(none) shared(rp, ci, va, xr, yw, n, shift)
                for (std::size_t src = 0; src < n; ++src) {
                    double sum = 0.0;
                    for (std::uint64_t p = rp[src]; p < rp[src + 1]; ++p) {
                        sum += va[p] * xr[ci[p]];
                    }
                    const std::size_t out = (src + shift) % n;
                    yw[out] = sum;
                    ss += sum * sum;
                }

                const double inv = 1.0 / std::sqrt(ss);

                // Phase B: scale the entries produced this iteration. The output
                // indices (src + shift) % n form a permutation of [0, n), so this
                // scales the whole written buffer.
                #pragma omp taskloop grainsize(grain) \
                    default(none) shared(yw, n, shift, inv)
                for (std::size_t src = 0; src < n; ++src) {
                    const std::size_t out = (src + shift) % n;
                    yw[out] *= inv;
                }
            } // implicit barrier: all writes visible before the next iteration
        }

        // Phase 3: final diagnostics, inside the timed region as in the
        // sequential code. After NUM_ITERS (even) iterations the final vector is
        // in buf0; the extra SpMV uses the final shift and is written into buf1.
        #pragma omp single
        {
            const std::size_t epochs_final = (NUM_ITERS - 1) / EPOCH_LEN;
            const std::size_t shift_final  = (shift_rows * epochs_final) % n;

            const double* xf = buf0.data();   // final x
            double*       ye = buf1.data();   // extra y = A_shifted * x

            double dot_xy = 0.0;
            #pragma omp taskloop grainsize(grain) reduction(+: dot_xy) \
                default(none) shared(rp, ci, va, xf, ye, n, shift_final)
            for (std::size_t src = 0; src < n; ++src) {
                double sum = 0.0;
                for (std::uint64_t p = rp[src]; p < rp[src + 1]; ++p) {
                    sum += va[p] * xf[ci[p]];
                }
                const std::size_t out = (src + shift_final) % n;
                ye[out] = sum;
                dot_xy += xf[out] * sum;   // contribution to dot(x, y)
            }
            rayleigh = dot_xy;
        }
    }

    // The final vector is in buf0. The checksum (order independent) is computed
    // here, still inside the timed region as in the sequential reference.
    const std::uint64_t checksum = checksum_vector(buf0);

    if (final_vector != nullptr) {
        *final_vector = std::move(buf0);
    }

    return IterativeResult{
        .rayleigh = rayleigh,
        .checksum = checksum,
        .final_row_shift = (shift_rows * ((NUM_ITERS - 1) / EPOCH_LEN)) % n
    };
}


int main(int argc, char** argv) {
    // Phase 0: read problem size, sparsity mode, seed, threads, dump path.
    std::uint64_t n64     = 0;
    std::uint64_t nz      = 0;
    std::uint64_t seed    = 111;
    std::uint64_t threads = 0;
    std::string mode;
    std::string dump_vector_path;

    if (!read_arg_u64(argc, argv, "-n", n64) ||
        !read_arg_u64(argc, argv, "-nz", nz) ||
        !read_arg_str(argc, argv, "-m", mode)) {
        usage(argv[0]);
        std::cerr << "  -t   Optional number of threads (default: OMP runtime default)\n";
        return 1;
    }

    // Optional arguments.
    (void)read_arg_u64(argc, argv, "-s", seed);
    (void)read_arg_str(argc, argv, "--dump-vector", dump_vector_path);
    if (!read_arg_u64(argc, argv, "-t", threads)) {
        (void)read_arg_u64(argc, argv, "--threads", threads);
    }

    unsigned num_threads = static_cast<unsigned>(threads);
    if (num_threads == 0) {
        num_threads = static_cast<unsigned>(omp_get_max_threads());
        if (num_threads == 0) num_threads = 1;
    }

    const std::size_t n = static_cast<std::size_t>(n64);
    std::cout << "SPARSE_ITERATION_OMP_TASKS\n";

    try {
        // Phase 1: input construction (not included in computation time).
        const auto tg0 = std::chrono::steady_clock::now();
        const GeneratedMatrix G = generate_matrix(n, nz, seed, mode);
        const auto tg1 = std::chrono::steady_clock::now();

        const double generation_sec = std::chrono::duration<double>(tg1 - tg0).count();

        print_matrix_stats(G);
        std::cout << "threads=" << num_threads << "\n";
        std::cout << "generation_time_sec=" << generation_sec << "\n\n";

        std::vector<double>  final_vector;
        std::vector<double>* final_vector_out = dump_vector_path.empty() ? nullptr : &final_vector;

        // Phase 2: timed iterative computation.
        const auto tc0 = std::chrono::steady_clock::now();
        const IterativeResult result =
            iterative_spmv_evolving_omp(G.A, seed, num_threads, final_vector_out);
        const auto tc1 = std::chrono::steady_clock::now();

        const double computation_sec = std::chrono::duration<double>(tc1 - tc0).count();

        std::cout << std::setprecision(15);
        std::cout << "rayleigh=" << result.rayleigh << "\n";
        std::cout << "checksum=0x" << std::hex << result.checksum << std::dec << "\n";

        std::cout << std::fixed << std::setprecision(6);
        std::cout << "Time (sec) = " << computation_sec << "\n";

        // Phase 3: optional correctness support, outside the timed region.
        if (!dump_vector_path.empty()) {
            dump_vector(dump_vector_path, final_vector);
            std::cout << "vector_dump=" << dump_vector_path << "\n";
        }
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
